runtime: php55
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /google094ff15990fcfd92\.html
  static_files: google094ff15990fcfd92.html
  upload: google094ff15990fcfd92\.html

- url: /bootstrap
  static_dir: bootstrap

- url: /RageAdventureWeb
  static_dir: RageAdventureWeb

- url: /.*
  script: index.html

